FROM python:3.6

#WORKDIR /home/app
WORKDIR /app

COPY .. .

RUN pip install -U pip
RUN pip install -r requirements.txt

#CMD ["pytest", "--url=http://192.168.0.105/", "--remote_type=selenoid", "tests/admin_part/test_admin_auth_zone.py::TestAuthorization"]
#pytest tests/test_github_list_repos_for_user.py --method=get --alluredir allure-reports && pytest tests/test_github_create_new_repos.py --method=post --alluredir allure-reports && pytest tests/test_github_create_new_branch.py --method=post --alluredir allure-reports

ENTRYPOINT ["pytest", "--alluredir", "allure-reports"]

CMD ["--method=get", "tests/test_github_list_repos_for_user.py"]
CMD ["--method=post", "tests/test_github_create_new_repos.py"]
CMD ["--method=post", "tests/test_github_create_new_branch.py"]
